import type {Metadata} from "next";
import localFont from "next/font/local";
import "./globals.css";
import Image from "next/image";
import NavBar from "@/components/NavBar";

const geistSans = localFont({
    src: "./fonts/GeistVF.woff",
    variable: "--font-geist-sans",
    weight: "100 900",
});
const geistMono = localFont({
    src: "./fonts/GeistMonoVF.woff",
    variable: "--font-geist-mono",
    weight: "100 900",
});

export const metadata: Metadata = {
    title: "CHESSVISION",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}>
        {/*
         We add flex + min-h-screen on the body so that
         the footer stays at the bottom if desired,
         and the middle area can grow/shrink.
      */}
        <body className="antialiased flex flex-col min-h-screen font-[family-name:var(--font-geist-mono)]">
        <NavBar/>

        {/* Main content flexes to fill available space */}
        <main className="flex-1">{children}</main>

        {/* Footer at the bottom */}
        <footer className="flex gap-6 flex-wrap items-center justify-center p-4 border-t dark:border-gray-700">
            <a
                className="flex items-center gap-2 hover:underline hover:underline-offset-4"
                href="https://github.com/CHESSVISION/"
                target="_blank"
                rel="noopener noreferrer"
            >
                <Image
                    aria-hidden
                    src="/github.svg"
                    alt="github icon"
                    width={16}
                    height={16}
                />
                Github
            </a>
            <a
                className="flex items-center gap-2 hover:underline hover:underline-offset-4"
                href="https://www.instagram.com/kuisskui"
                target="_blank"
                rel="noopener noreferrer"
            >
                <Image
                    aria-hidden
                    src="/person.svg"
                    alt="person icon"
                    width={16}
                    height={16}
                />
                kuisskui
            </a>
            <a
                className="flex items-center gap-2 hover:underline hover:underline-offset-4"
                href="https://www.instagram.com/banana._.zzz/"
                target="_blank"
                rel="noopener noreferrer"
            >
                <Image
                    aria-hidden
                    src="/person.svg"
                    alt="person icon"
                    width={16}
                    height={16}
                />
                bananaz
            </a>
        </footer>
        </body>
        </html>
    );
}
